### PR TITLE
Added dark mode for cta button 

### PR DESCRIPTION
**Pull request by sheridanvk**
Remix: https://glitch.com/edit/#!/spiny-arrow-eel

We are starting to use notifications in the editor, but there's no dark mode for the CTA button. I coped what we have in the editor right now, but I'm very open to other suggestions - or we could just go with this for now and revisit later.

Before:
Screenshot 2020-04-29 at 2 44 54 PM
Screenshot 2020-04-29 at 3 03 25 PM

After:
Screenshot 2020-04-29 at 2 51 38 PM
Screenshot 2020-04-29 at 2 53 13 PM

### CODE REVIEW

**Comment by sheridanvk** [comment]
Additionally this is what we actually have the editor for onboarding notifications right now (rather than the pale blue in the screenshots above); is this preferable to the existing dark mode notification colour? I can change that too as needed

Screenshot 2020-04-29 at 3 06 25 PM

**Comment by ackristen** [comment]
Hi @sheridanvk! My Figma is down right now so I can't see what colours we have to choose from. 

I am good with having a purple cta + darker blue background as you've selected. Is the dark blue #3167AC?

**Comment by sheridanvk** [comment]
great thank you! No it's #006280 - you can see the dark mode colours we use in the editor that aren't in shared-components yet here https://github.com/glitchdotcom/Glitch-Editor/blob/master/styles/themes/cosmos.styl#L100 (I am definitely in favour of getting these all into shared-components, so happy to work on/help with that as and when you want to do that).

I'm totally fine with using #3167AC instead though - added it to the remix, and I put the app into the Glitch team so you can join and edit if you want to tweak the colours and see what they look like: 
Screenshot 2020-04-30 at 11 49 49 AM

To do that just change the colours you want for onboarding text and background here:
https://glitch.com/edit/#!/spiny-arrow-eel?path=lib%2Fthemes.js%3A85%3A9
and then go to the app https://spiny-arrow-eel.glitch.me/ and select darkTheme at the top, and navigate to Notifications > Create Onboarding Notification

**Comment by keithk** [comment]
:rocket: PR was released in [`v0.19.0`](https://github.com/glitchdotcom/shared-components/releases/tag/v0.19.0) :rocket:

**Pull request merged**
